### ISSUE TITLE
Error: undefined is not an object (evaluating 'InnerNativeModule.installCoreFunctions')

### ISSUE THREAD

**Issue by ChenDimri** [GetStream/stream-chat-react-native#1111]
I'm getting this error on ios, seems to be related to reanimated library.

I'm using these versions:
"react-native-reanimated": "2.3.1"
"stream-chat-react-native": "3.10.2"

gz#18853

**Comment by vishalnarkhede** [comment]
Hey @ChenDimri We will need some more information to be able to reproduce this on our side. If you can setup a simple app with reproducible issue and share it with us, that would be great.

Also please make sure you have followed all the setup steps from here - https://getstream.io/chat/docs/sdk/reactnative/

**Comment by vadimT-blanket** [comment]
We had the same issue - it was related to incorrect RN upgrade.
The problem is in this Reanimated code:
`const InnerNativeModule = global.__reanimatedModuleProxy;`
Reanimated sets `global.__reanimatedModuleProxy` correctly only if RNBridge is initialized via initWithDelegate (AppDelegate.m), like:
`RCTBridge *bridge = [[RCTBridge alloc] **initWithDelegate**:self launchOptions:launchOptions];`
but not in an old way:
RCTBridge *bridge = [[RCTBridge alloc] **initWithBundleURL**:jsCodeLocation ...

**Comment by vadimT-blanket** [comment]
@ChenDimri , created a new RN project and checked how bridge initialization works now, in my case I changed:
1. AppDelegate.h - added RCTBridgeDelegate
@interface AppDelegate : UIResponder <UIApplicationDelegate, **RCTBridgeDelegate**, UNUserNotificationCenterDelegate>
2. AppDelegate.m - moved bundle URL logic to a separate method, like:
`
- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [CodePush bundleURL];
#endif
}
`
3.  Replaced 
`RCTBridge *bridge = [[RCTBridge alloc] initWithBundleURL:jsCodeLocation ...`
with 
`RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];`

**Comment by ChenDimri** [comment]
@vadimT-blanket  Thank you, it works for me too!
