### ISSUE TITLE
Translation not applying on channels list

### ISSUE THREAD

**Issue by ChenDimri** [GetStream/stream-chat-react-native#1146]
**Describe the bug**
Hi, I added a translation file in Hebrew because our app is in Hebrew.
I followed the steps regarding the translation that are mentioned in the documentation and I see Hebrew in the channel,
but in the channels list I still see the text in English (adding screenshots).

This is what I did in the code:

const streami18n = new Streami18n();
streami18n.registerTranslation('he', hebrewTranslation, hebrew);
streami18n.setLanguage('he');

      <Chat client={chatClient} i18nInstance={streami18n}>
        <OverlayProvider bottomInset={bottom} i18nInstance={streami18n}>

Is there any additional code that I need to add in order to see Hebrew in the channels list?

**Dev environment info (please complete/provide the following information):**

-stream-chat-react-native 3.01.2
- react-native 0.63.3
-Emulator

**Screenshots**
![Simulator Screen Shot - iPhone 11 - 2022-02-14 at 16 18 39](https://user-images.githubusercontent.com/92083836/153881148-e656a163-f8c3-4dff-b883-0b59f49069e1.png)

![Simulator Screen Shot - iPhone 11 - 2022-02-14 at 16 18 52](https://user-images.githubusercontent.com/92083836/153881222-43c682b6-13ab-4c8a-9dfd-8801befac959.png)

gz#19554

**Comment by vishalnarkhede** [comment]
For internal tracking - https://stream-io.atlassian.net/browse/CRNS-522

**Comment by ChenDimri** [comment]
@vishalnarkhede Is there any anticipation for when this fix will happen?
I managed to fix it on ChallengeList in the library to see if it's possible/complicated to do.
But If I'm understanding right then I can't send a custom ChallengeList and have to use the default one..

**Comment by khushal87** [comment]
@ChenDimri Did you go through this guide - https://getstream.io/chat/docs/sdk/reactnative/basics/translations/#overriding-datetime-format and added the translations for `he` language?

**Comment by ChenDimri** [comment]
@khushal87 Yes, but it's not working for channel list component as I mentioned and as @vishalnarkhede said, it's a bug that's going to be fixed

**Comment by khushal87** [comment]
From what I can find, the `he` language of the DayJS package doesn't support AM/PM maybe because the language `he` doesn't have AM/PM - https://github.com/iamkun/dayjs/blob/dev/src/locale/he.js. I checked the same using `hi`(Hindi) language and it works fine.

Anyways we have a configuration that can be done in languages as:

```tsx
import Dayjs from 'dayjs';
import updateLocale from 'dayjs/plugin/updateLocale';

Dayjs.extend(updateLocale);

Dayjs.updateLocale('hi', {
  /**
   * Hindi notation for meridians is quite fuzzy in practice. While there exists
   * a rigid notion of a 'Pahar' is not used as rigidly in modern Hindi.
   */
  meridiem(hour: number) {
    if (hour < 4) return 'रात';
    if (hour < 10) return 'सुबह';
    if (hour < 17) return 'दोपहर';
    if (hour < 20) return 'शाम';
    return 'रात';
  },

  meridiemHour(hour: number, meridiem: string) {
    if (hour === 12) {
      hour = 0;
    }
    if (meridiem === 'रात') return hour < 4 ? hour : hour + 12;
    if (meridiem === 'सुबह') return hour;
    if (meridiem === 'दोपहर') return hour >= 10 ? hour : hour + 12;
    if (meridiem === 'शाम') return hour + 12;
    return hour;
  },

  meridiemParse: /रात|सुबह|दोपहर|शाम/,
});

export const streami18n = new Streami18n({
  language: 'hi',
  DateTimeParser: Dayjs,
});
```

The following works because the language `hi` supports `A`(https://github.com/iamkun/dayjs/blob/dev/src/locale/hi.js#L12-L19) in format unlike `he`(https://github.com/iamkun/dayjs/blob/dev/src/locale/he.js#L51-L62).

<img src="https://user-images.githubusercontent.com/39884168/157193704-591d10ae-8c91-46d8-82db-c3f1d83a7c77.png" width="400px" height="750px" />

@ChenDimri Let me know if you have any doubt.

**Comment by khushal87** [comment]
Hey @ChenDimri, the following attached snippet would work for you.

```tsx
import { Streami18n } from 'stream-chat-react-native';
import Dayjs from 'dayjs';
import 'dayjs/locale/he';
import updateLocale from 'dayjs/plugin/updateLocale';
/**
 * Start playing with streami18n instance here:
 * Please refer to the description of this PR for details: https://github.com/GetStream/stream-chat-react-native/pull/150
 */

Dayjs.extend(updateLocale);

Dayjs.updateLocale('he', {
  formats: {
    LT: 'hh:mm A',
  },

  meridiem(hour: number) {
    if (hour < 4) return 'रात';
    if (hour < 10) return 'सुबह';
    if (hour < 17) return 'दोपहर';
    if (hour < 20) return 'शाम';
    return 'रात';
  },

  meridiemHour(hour: number, meridiem: string) {
    if (hour === 12) {
      hour = 0;
    }
    if (meridiem === 'रात') return hour < 4 ? hour : hour + 12;
    if (meridiem === 'सुबह') return hour;
    if (meridiem === 'दोपहर') return hour >= 10 ? hour : hour + 12;
    if (meridiem === 'शाम') return hour + 12;
    return hour;
  },

  meridiemParse: /रात|सुबह|दोपहर|शाम/,
});

export const streami18n = new Streami18n({
  language: 'he',
});

```

Please don't forget to add your language translations in `meridiem`, `meridianHour`, and `meridiemParse`. I have used `Hindi(hi)` as the language to test. The problem here was that, the `he` language doesn't have meridian in their format by default so you have to customize it as above(note I have added `A` along with `hh:mm` in the format's object).

Also finally don't forget to provide the `streami18n` instance to the Chat component in the `i18nInstance` prop.

Hope this is gonna help you 😄 

@ChenDimri Please close the issue if its resolved. Thanks 😄

**Comment by vishalnarkhede** [comment]
@ChenDimri pardon me for confusion, but what @khushal87 suggested is correct :)
