### ISSUE TITLE
Issue with stream-chat-expo compatibility with Expo 44

### ISSUE THREAD

**Issue by JSimai** [GetStream/stream-chat-react-native#1161]
Hi!
I'm simply trying to install stream-chat-expo in my new expo project, but there is a dependency error coming up that I can't figure out regarding my expo version.

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native/stream-chat-expo): 
v3.10.2
Latest
on 24 Nov 2021

- react-native or expo version:
SDK 44

**To Reproduce**
Tried to run: npm i stream-chat-expo
See error.

**Expected behavior**
Expected it to install!

**Screenshots**
![Screen Shot 2022-02-25 at 1 59 53 pm](https://user-images.githubusercontent.com/67139031/155645485-9d6553f1-085c-43f4-9192-cac180625382.png)

gz#19999

**Comment by vishalnarkhede** [comment]
@JSimai could you please try `expo install stream-chat-expo` instead?

**Comment by vishalnarkhede** [comment]
Also you may need to use `--legal-peer-deps` in this case, since yarn 2 added strict rules for peer dependencies.

**Comment by madsroskar** [comment]
I think that was a typo, `--legacy-peer-deps` should be the flag to use. Alternately `--force`. These are also hinted at at the bottom of the screenshot you added.

The error is raised since a new expo project set up with `expo init` right now will use expo version `~44.0.0` and the SDK has set version `~41.0.1`, I'll make a PR to update this in the SDK to allow version 44 of expo once I've been able to test it out a bit more. This error will be raised with `npm`, but are considered warnings by `yarn` (classic/1.x.x). I'm not sure how `pnpm` treats it, but I'd assume it raises an error there too(?).

Until the peer dependency requirement is changed in the SDK, the workaround for this in your app, without downgrading the expo version, is to add either `--force` or `--legacy-peer-deps` when installing `stream-chat-expo`.

**Comment by JSimai** [comment]
Thanks for the help! I installed it, then also forced the subsequent package installs as outlined at https://getstream.io/chat/docs/sdk/reactnative/
Running the app after that resulted in some more errors which seem quite scary
![Screen Shot 2022-03-04 at 6 18 16 pm](https://user-images.githubusercontent.com/67139031/156717434-f1460ca4-90c2-4c36-9327-67dbf3f29e24.png)
Should I just leave this until expo 44 is allowed?

**Comment by vishalnarkhede** [comment]
Hey @JSimai reanimated dependency requires you to add additional babel plugin as mentioned in their docs - https://docs.expo.dev/versions/latest/sdk/reanimated/#installation

**Comment by JSimai** [comment]
Hey @madsroskar is there any update on the progress of making stream chat compatible with Expo 44?

**Comment by vishalnarkhede** [comment]
@JSimai the sdk is already compatible with expo 44. Please check our example app - https://github.com/GetStream/stream-chat-react-native/blob/develop/examples/ExpoMessaging/package.json#L14

**Comment by JSimai** [comment]
Hi Vishal,

Reinstalling stream-chat-expo still says that it expects Expo 41.0.1.

**Comment by JSimai** [comment]
Hi there,

Is there any update on this?

**Comment by vishalnarkhede** [comment]
@JSimai 

> Reinstalling stream-chat-expo still says that it expects Expo 41.0.1.

Yes this is expected at this point, but SDK is completely compatible with expo 44. We will update the peer dependencies within project soon. But this shouldn't be a blocker for you as explained by @madsroskar in his response.

**Comment by JSimai** [comment]
Oh I see, thank you for the clarification! I appreciate the updates!
Legendary :)
