### ISSUE TITLE
undefined is not an object (evaluating 'message.type')

### ISSUE THREAD

**Issue by cleandevcode** [GetStream/stream-chat-react-native#1207]
My stack:
stream-chat: 6.1.0
stream-chat-expo: ^4.1.0
expo: ^40.0.0

I am going to customize the message component by using `MessageSimple`
This Customized `MessageSimple` component will be rendered in `MessageList`.

But I see this error.
![image](https://user-images.githubusercontent.com/52365167/158182599-3fe59ade-b178-4a34-b039-35d91504790b.png)

Can you please help me?

gz#20612

**Comment by vishalnarkhede** [comment]
@cleandevcode could you please share some code around customization?

**Comment by cleandevcode** [comment]
@vishalnarkhede 
For sure.

- CustomMessageList
`
<MessageList
 TypingIndicator={CustomTypingIndicator}
 DateDeparator={CustomDateSeparator}
 //Message={(props) => <CustomMessage {...props} />}
/>
`

- CustomMessage
`
<MessageSimple 
{...props}
message={message}
enableMessageGroupingByUser
style={customStyle}
groupStyles={[`middle`]}
UrlPreview={CustomUrlPreview}
showMessageStatus={false}
)}
/>
`


Actually `message.type` did have the value `regular`

**Comment by vishalnarkhede** [comment]
@cleandevcode couple of things:

- You should be providing prop `MessageSimple` instead of `Message`.
- This prop should be provided to `Channel` component
- Also message object should be accessed from `MessageContext` context.

For reference, please follow our docs https://getstream.io/chat/docs/sdk/reactnative/guides/message-customization/#messagesimple

**Comment by cleandevcode** [comment]
@vishalnarkhede Thank you for your message.
Yeah, I could fix the issues by following the guideline.
