### ISSUE TITLE
Add support for automatic translations

### ISSUE THREAD

**Issue by madsroskar** [GetStream/stream-chat-react-native#1255]
Add support for automatic translations of messages, currently the SDK doesn't support it.

This will affect MessageText and ChannelPreview

**Comment by vishalnarkhede** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/React-Native-SDK-62285abeb7c8e800229effc5/issues/GetStream/stream-chat-react-native/1255?planning-poker) with ZenHub @Enigma-I-am @khushal87 @madsroskar @santhoshvai

**Comment by semmons99** [comment]
Hey all. Just wanted to say that this would be a huge unlock for our user base if you could get this implemented soon.

For reference, we are an edtech startup that provides administration and communication services for everything outside of the classroom. huge swaths of our users are unable to communicate with their kids coaches because of the language barrier. this feature would all parents to finally hear how awesome their kids are, and their potential for improvement that could lead them to be a first-generation college grad.

I know this may be sappy, but it is 100% one of the biggest reasons we picked stream to power our communications. please let us know what we might do to help get this implemented soon.

**Comment by chompasina** [comment]
Hey Stream folks, big +1 to @semmons99's post above. We've tracked down where we can see the translation coming back from Stream, and for some reason it's just not getting rendered in the chat. Let us know if we can provide any other documentation or pair with y'all as you move forward with this. We're really excited to bring this to our users.

**Comment by vanGalilea** [comment]
@semmons99 Thanks for reaching out.
We're very close to finishing this feature. Stay tuned by following this issue.

**Comment by semmons99** [comment]
you have no idea how huge this is for our customers. thank you @vanGalilea we will keep a lookout for it

**Comment by semmons99** [comment]
@vanGalilea any update?

**Comment by madsroskar** [comment]
Hi, @semmons99 - hopefully we'll have this available in a beta release this week - I'll update you here once it's there

**Comment by semmons99** [comment]
@madsroskar any update?

**Comment by semmons99** [comment]
@madsroskar we are set to release July 18, what is the likelihood of seeing this fix? Do we need to start informing our customers this will not be working?

**Comment by chompasina** [comment]
@madsroskar is this still open? Just wanted to check in.

**Comment by madsroskar** [comment]
Hi - sorry for the lack of response, somehow I've not seen the notifications from this thread.

I have a [PR](https://github.com/GetStream/stream-chat-react-native/pull/1526) up for it, as soon as it's reviewed and tested I'll be able to merge and release it. Hoping to be able to do so today, worst case later this week.
