### ISSUE TITLE
Android keyboard automatically appears on clicking attach button.

### ISSUE THREAD

**Issue by bijobaby-2009** [GetStream/stream-chat-react-native#1574]
In android phones on clicking attach button keyboard automatically appears. This happens whenever TextInput is active.

Tried `Keyboard.dismiss(); ` and it is not working. 

Issue found only in android. In ios it is working fine.

Stream chat version checked - 3.9.0

Expected Behaviour
--------------------
No need to show keyboard on clicking the attach button

Issue
-----
https://user-images.githubusercontent.com/57980419/179940054-3f764004-2d31-4230-a7b3-783c52d2ff5d.mov

**Comment by vanGalilea** [comment]
@bijobaby-2009, thanks for reaching out. You're currently using a very outdated version. I recall that this issue has been fixed in the past. We advise you to upgrade to the latest stable version [4.12.0](https://github.com/GetStream/stream-chat-react-native/releases/tag/v4.12.0).

We've also created a [guide](https://getstream.io/chat/docs/sdk/reactnative/basics/upgrading-from-v3/) that will assist you in upgrading from v3 to v4.

I'll be closing this for now. Please don't hesitate to contact us, may you have any issues/questions in the future.
