### ISSUE TITLE
Username mentions with a dot are rendered as links. 

### ISSUE THREAD

**Issue by santhoshvai** [GetStream/stream-chat-react-native#1666]
This was reported by a customer from zendesk: https://getstream.zendesk.com/agent/tickets/26580

> User mentions with a dot in the username are being rendered as a link and not a user mention. I think the issue is in package/src/components/Message/MessageSimple/utils/parseLinks.ts. In web3, it's really common for users to have usernames like "grant.eth" so this affects most of our most engaged users. This works as expected in the React SDK.

**Comment by vanGalilea** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/React-Native-SDK-62285abeb7c8e800229effc5/issues/GetStream/stream-chat-react-native/1666?planning-poker) with ZenHub @madsroskar @vishalnarkhede

**Comment by madsroskar** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/React-Native-SDK-62285abeb7c8e800229effc5/issues/GetStream/stream-chat-react-native/1666?planning-poker) with ZenHub @santhoshvai

**Comment by grantmagdanz** [comment]
I upgraded to 5.3.1, and it seems this is only partially fixed. While the SDK does recognize mentions with `.` as mentions it only renders up until the dot. The onPress also does not work because it cannot find the mentioned user (i.e. `additionalInfo.user` is `undefined`).

I think it might have somethign to do with this line:

```
const userName = node.content[0]?.content?.substring(1);
```

at https://github.dev/GetStream/stream-chat-react-native/blob/f41e9fdda5a40dc795cbf3acce896d6b632995fe/package/src/components/Message/MessageSimple/utils/renderText.tsx#L222
