### ISSUE TITLE
Attachment picker tabs gets hidden when an Image/Attachment is selected on Android

### ISSUE THREAD

**Issue by khushal87** [GetStream/stream-chat-react-native#1700]
**Describe the bug**

The attachment picker tabs with image, file and camera picker are hidden when an image is selected from the image picker.

**Dev environment info (please complete/provide the following information):**

- Package version - 5.1.0
- Android only

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to Message input in a channel
2. Select an image from the Image picker
3. Notice that the tabs get hidden when the image is selected

**Expected behaviour**
The tabs should be clearly visible.

**Additional context**
NIL

**Screenshots**
https://images.zenhubusercontent.com/178163307/1f3b6406-ff32-465d-a5cb-a6de9d347735/screen_recording_2022_09_02_at_15_42_25.mov

**Comment by vanGalilea** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/React-Native-SDK-62285abeb7c8e800229effc5/issues/GetStream/stream-chat-react-native/1700?planning-poker) with Zenhub @khushal87 @santhoshvai

**Comment by vanGalilea** [comment]
This issue must be solved in all places once and for all. 
We should calculate the snap points of the bottom sheet dynamically and use the same logic everywhere (Screen vs. window dimensions etc.)

**Comment by vanGalilea** [comment]
This issue is not reproducible anymore, therefore it will be closed

**Comment by Stofkat** [comment]
This seems to happen again on some Android devices i.e. reproducable on a AVD Pixel 4 to a lesser extend and Pixel 6 pro more prominently. 

See screenshot.

I've tried using `bottomInset` with `OverlayProvider` as suggested in another issue, but that doesn't work because even using calculations for screen height and navigation bar height lead to different result on different devices.

<img width="377" alt="Screenshot 2023-12-06 at 12 33 48" src="https://github.com/GetStream/stream-chat-react-native/assets/7677462/5a27e41b-a142-4eaa-b583-91513ce0991e">
