### ISSUE TITLE
offline support v5

### ISSUE THREAD

**Issue by akanz** [GetStream/stream-chat-react-native#1729]
Good day,
I am trying to configure my app for offline support. I followed the migrate to v5 and enable offline support doc, but I keep getting 
"Please install react-native-quick-sqlite" package to enable offline support. I have installed and ran pod install but same error. 
Any help will be appreciated.

**Comment by santhoshvai** [comment]
Hi @akanz , this is most likely because react-native-quick-sqlite did not install correctly. Can you please remove node_modules and yarn.lock and then do a clean install again?. 

Also we have noticed in our macs that react-native-quick-sqlite installation fails when the default python of mac is not found and if the mac is dependent on homebrew's python.In that case, please do `ln -s -f /opt/homebrew/bin/python3 /usr/local/bin/python` to specify a local/bin python for the package installation to work.
