### ISSUE TITLE
Change color top handle of attachment bottom sheet

### ISSUE THREAD

**Issue by GarryLaly** [GetStream/stream-chat-react-native#1783]
**Describe the bug**
We difficult to change the top handler of bottom sheet for attachment. How we can change it?

**Dev environment info (please complete/provide the following information):**

- Package version stream-chat-react-native 5.3.0
- react-native 0.67.1
- Device(Android Samsung A51) and OS version android 12 (One UI version 4.1)

**To Reproduce**

1. Go to chat message 
2. Click on icon attachment
3. See error top handler of bottomsheet, need to change background

**Expected behavior**
Changing custom background for top handler of bottomsheet 

**Screenshots**
![image](https://user-images.githubusercontent.com/5617788/200031745-0efa2020-505a-46d1-a09b-c11b592ad4df.png)

**Comment by madsroskar** [comment]
Hi, @GarryLaly.

There are two separate components to customize here. For the top bar with the icons, setting the background color in the theme would look something like:

```
{
    theme: {
        attachmentSelectionBar: {
            container: {
                backgroundColor: 'red',
            },
        },
    }
}
```

The handle on the bottom sheet (right below) will by default use the colors set in the `theme.colors` object, setting the background color to whatever color you've defined as `black`. 

Since that doesn't at the moment have any overrides in the theme object, I think the easiest way to go about customizing it would be to make a copy of our [`AttachmentPickerBottomSheetHandle`](https://github.com/GetStream/stream-chat-react-native/blob/develop/package/src/components/AttachmentPicker/components/AttachmentPickerBottomSheetHandle.tsx) component, and passing that to the `Channel` component to override the default implementation.

**Comment by GarryLaly** [comment]
@madsroskar solve with copy of `AttachmentPickerBottomSheetHandle` and passing to the `OverlayProvider`. Thanks
