### ISSUE TITLE
Allow customization of `useMessageNew`

### ISSUE THREAD

**Issue by madsroskar** [GetStream/stream-chat-react-native#1796]
**Motivation**

We can currently only pass `lockChannelOrder` to override the functionality of [useMessageNew](https://github.com/GetStream/stream-chat-react-native/blob/develop/package/src/components/ChannelList/hooks/listeners/useNewMessage.ts) that bumps channels up to the top of the channel list when a new message arrives. However, for some cases (multiple channel lists filtered by channel type for example), it would be helpful to override this functionality in a different way than `lockChannelOrder` does.

**Proposed solution**
Allow passing a function to override the funcitonality of `useMessageNew`

**Comment by vanGalilea** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/React-Native-SDK-62285abeb7c8e800229effc5/issues/GetStream/stream-chat-react-native/1796?planning-poker) with Zenhub @madsroskar @santhoshvai @vishalnarkhede

**Comment by vishalnarkhede** [comment]
## Proposal

- Introduce new properties So there’s a clear distinction between events and notifications
  - `onNewMessageEvent` which handles `message.new` event
  - `onNewMessageNotification` which handles `notification.message_new` event.

- Leave the `onMessageNew` working as is, mark it as obsolete/deprecated and keep it working for at least 1 more major version cycle, or even multiple major cycles. Also add comment explaining that this is a notification and not an event and that the `onNewMessageEvent` and `onNewMessageNotification` are the recommended properties to use
I think It’s very important to not break the code of customers that simply want to upgrade to get the new fixes. Only major updates are acceptable to break backward compatibility because they bring something bigger to the table

**Comment by aharwood9** [comment]
Hi 👋 Sorry, I totally missed this issue when I generated this [PR](https://github.com/GetStream/stream-chat-react-native/pull/1913). I am happy to update this to @vishalnarkhede proposal if that works. Sorry to pester but we are close to releasing a feature that splits channel lists by channelType and this is causing us a lot of issues.

**Comment by aharwood9** [comment]
Hopefully not too keen but I've updated that PR to conform to the proposal. I will start working on the docs now but would be great to know if this is generally acceptable.
