### ISSUE TITLE
Error loading messages for this channel

### ISSUE THREAD

**Issue by cleandevcode** [GetStream/stream-chat-react-native#1820]
Hello

My Packages:
```
"stream-chat": "6.1.0",
"stream-chat-react-native": "^5.0.0",
```

When I enter the chat box, I see the error called `Error loading messages for this channel...`
But channel ID was existing in GetStream Dashboard.

[Notes];
And this channel was the new one which is not used yet. (So `last_message_at` is still undefined).
But I am 99% sure it worked before.

What will be the reason?
Thanks.

**Comment by vishalnarkhede** [comment]
@cleandevcode 

- minimum required version of `stream-chat` is v7 for v5 of `stream-chat-react-native`. I would advice you to avoid explicitely installing `stream-chat` dependency. So that package manager will install the specificed version by default.
- Are you using offline support? Basically have you set `enableOfflineSupport` prop on `Chat` component?
- Are you using standalone Channel component? Or combination of ChannelList and Channel component?

**Comment by cleandevcode** [comment]
@vishalnarkhede 
1. I don't use offline support.
2. I am using the customized `ChannelPreview` and `ChatThread`.

So clicking the channel preview from the Channel List, then it will navigate to `ChatThread`.
Then `ChatThread` is designed following:

```
<Chat client={client}>
   <Channel channel={channelRef} thread={thread}>
      <CustomView />
   </Channel>
</Chat>
```

It works fine for other channels (They already have the chat history).
But it does not work fine for only channels (It does not have the chat history) / But the channel ID is existing in the Dashboard.


Regards.

**Comment by cleandevcode** [comment]
Thanks, @vishalnarkhede 
It worked after upgrading the version of `steam-chat` v7.

Thanks.
