### ISSUE TITLE
Private channels - possible props which always return data of the opposite member

### ISSUE THREAD

**Issue by carolinaknoll** [GetStream/stream-chat-react-native#1833]
**Motivation**
When I create a private channel which has only two users, I have a header on the screen of the channel which shows a name and an image. 

I noticed that I have to manually filter the channel `members` array for the user that is not equal to my current user, and _then_ use this information to populate the header with the name of this other user, and the respective image of this other user.

I have to do this because if I, user A, create a private chat with user B, and pass the name and image of user B as a custom prop for the `name` and `image` fields for the header, when the user B opens the same chat he will see his own name and image instead of mine. So I end up always having to do this check and get this info manually. It's not hard to do, but the code does get messier. 🤔 

**Proposed solution**
I'm not sure actually, stream-chat is quite complex so I'm unable to come up with a good solution for it. But maybe, giving that on the `connectUser` I can pass the name and the current image of my current user to get-stream, it could filter the `members` array of a private channel internally when this info is present for both users, and return some kind of `display_name`/`display_image` prop that would return the opposite name and image to be used on the header.

I'm bringing light to this issue because it seems to be a very common scenario, and I wasn't able to find anything in the documentation that would point me to a better way to do this. I also could be looking for the wrong thing, though! 😅  
I'm super okay if it isn't possible given that a channel can be created with very particular circumstances.

**Acceptance Criteria**
Given that I create a private channel with two users:
- When I access the channel, I will have access to information of the opposite user of the channel, to populate any UI component that requires it.
- If the opposite user accesses the same private channel, he will have access to information of my user to populate the components instead.

Thank you! 😄

**Comment by vishalnarkhede** [comment]
Hey @carolinaknoll thanks for the detailed information about requirement. I really appreciate since it helps us avoid back-and-forth for details.

I think this is quite a standard problem. We export following hooks from `stream-chat-react-native` sdk, which will be perfect fit for your usecase I think.

- [`useChannelPreviewDisplayAvatar`](https://github.com/GetStream/stream-chat-react-native/blob/develop/package/src/components/ChannelPreview/hooks/useChannelPreviewDisplayAvatar.ts#L57) This hook will give you the image url for channel depending on wether the channel is group channel or 1-1 conversation. For group channel, it uses it will provide `channel.data.image` as image property. But if it doesn't exist, then it will provide you image as other member's `user.image` value. If there are more than 1 (other) member, then it will give you array of images of other members.
- [`useChannelPreviewDisplayName`](https://github.com/GetStream/stream-chat-react-native/blob/develop/package/src/components/ChannelPreview/hooks/useChannelPreviewDisplayName.ts#L69) Similarly, this will provide you name for the channel. If channel.data.name exist, then it will be returned. Otherwise it returns names of other member of channel (comma separated)

We use these hooks internally to show avatar and channel name
- https://github.com/GetStream/stream-chat-react-native/blob/develop/package/src/components/ChannelPreview/ChannelAvatar.tsx#L26
- https://github.com/GetStream/stream-chat-react-native/blob/develop/package/src/components/ChannelPreview/ChannelPreviewMessenger.tsx#L130

**Comment by carolinaknoll** [comment]
Thank you so much for your reply! Yes, this seems to be precisely what I need, I'm glad you pointed these out. 🚀 

I'll test internally once I have some time to return to the part of my code that would require it. I'll reopen the issue if any more help is needed related to this.

Thanks a lot for the support!
