### ISSUE TITLE
Null pointer exception in QuickSqliteClient

### ISSUE THREAD

**Issue by mrwatts88** [GetStream/stream-chat-react-native#1843]
On this [line](https://github.com/GetStream/stream-chat-react-native/blob/develop/package/src/store/QuickSqliteClient.ts#L36), sqlite will be undefined when running on Expo, which causes the error:
```
undefined is not an object (evaluating 'sqlite.executeSql')
```

**Comment by vishalnarkhede** [comment]
:tada: A fix for this issue is included in version 5.6.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/stream-chat-react-native-core/v/5.6.1)
- [GitHub release](https://github.com/GetStream/stream-chat-react-native/releases/tag/v5.6.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:
