### ISSUE TITLE
Event channel.hidden doesn't hide the channel from the channel list

### ISSUE THREAD

**Issue by Antoine-C** [GetStream/stream-chat-react-native#187]
Hello,

**Describe the bug**
When a user is a member of a list of channels and one of them is hidden then the current list of channels is not updated to exclude the hidden one.

**Dev environment info (please complete/provide the following information):**

- Package version : stream-chat-react-native 0.10.0-rc.0
- RN : 0.61.5
- iOS simulator 13.3 (type iPhone 11).
- MacOS Catalina

**To Reproduce**
Create a simple One - One channel like this 

backend/index.js
```js
const channel = this._chat.channel("messaging", {
      members: ['thomas', 'eric'],
      created_by_id: 'eric'
    });
```
mobile/index.js

```js
const chatClient = new StreamChat("streamKey");
await chatClient.setUser(
  {
    id: "thomas",
  },
  "token" // -> It's replaced by the real token in my code
);
<Chat
  style={{
    colors: {
      primary: Config.getTheme("mainColor"),
    },
  }}
  client={chatClient}
  i18nInstance={streami18n}
>
    <ChannelList
      filters={{
        type: "messaging",
        members: { $in: ["thomas"] },
      }}
      sort={{ last_message_at: -1 }}
      Preview={ChannelPreviewMessenger}
      LoadingIndicator={() => (
        <ActivityIndicator size="large" color={Config.getTheme("mainColor")} />
      )}
      onSelect={(channel) => {
        Actions.chat({ chatClient, channel, streami18n });
      }}
    />
</Chat>;
```

Later on hide the channel like with the JS SDK 
```js
channel.hide('thomas');
```
**Misc**

I can see in the app the event and I get this in the console.log

```js
{
type: "channel.hidden"
cid: "id" // replaced
created_at: "2020-04-12T13:57:54.907965464Z"
clear_history: false
}
```

Also in [ChannelList.js](https://github.com/GetStream/stream-chat-react-native/blob/master/src/components/ChannelList.js#L335), there is no case for the **channel.hidden** event, so is this a wanted behavior ?

Thanks

**Comment by vishalnarkhede** [comment]
@Antoine-C thanks for bringing this up. It looks like ChannelList doesn't handle `channel.hidden` event. I will include it in next release :)

**Comment by Antoine-C** [comment]
Hi @vishalnarkhede
Awesome thanks ! Do you want a PR to tackle this or it's not necessary (given it's not a big change) ?

**Comment by vishalnarkhede** [comment]
@Antoine-C PR would be really helpful. If you are planning to file a PR, please try to check the following checklist:

- [ ] Channel gets removed from list when `channel.hidden` is received.

- [ ] Introduce a new prop - `onChannelHidden`, which can be used to override default handler, similar to `onMessageNew` or `onChannelTruncated`

- [ ] Add the new prop `onChannelHidden` to PropType list with little doc.

- [ ] Include the new prop to typescript file - https://github.com/GetStream/stream-chat-react-native/blob/master/types/index.d.ts#L422

Otherwise I will try to take care of this by end of this week or early next week. Thanks :)

**Comment by Antoine-C** [comment]
@vishalnarkhede not a problem I'll submit a PR by the end of the day
