### ISSUE TITLE
EXPO 47 Libraries not Working

### ISSUE THREAD

**Issue by gregdevvv** [GetStream/stream-chat-react-native#1887]
**Describe the bug**

Instead of Running the code returns the following error 
```
{"Exception thrown while executing UI block: -[__NSArrayM objectForKeyedSubscript:]: unrecognized selector sent to instance 0x6000011ec5d0

__53-[ABI47_0_0RCTUIManager flushUIBlocksWithCompletion:]_block_invoke
    ABI47_0_0RCTUIManager.m:1202
__53-[ABI47_0_0RCTUIManager flushUIBlocksWithCompletion:]_block_invoke.426
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_drain
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
-[UIApplication _run]
UIApplicationMain
main
start_sim
0x0
0x0
"}
```

**Dev environment info (please complete/provide the following information):**

- stream-chat-expo
- expo version
- IOS Emulator IOS 16

**To Reproduce**

Install the Modules with Expo 47 as the base of the project , and then run the example project for expo.

**Expected behavior**
On Expo 46 the chat was shown as needed with chat lists and everything working

**Additional context**
I tried to look up the error code and was not able to find anything that solved the issue.

**Screenshots**

**Comment by vanGalilea** [comment]
This might be related to this [issue](https://github.com/software-mansion/react-native-svg/issues/1337) 👀

**Comment by vanGalilea** [comment]
@gregdevvv tnx for reaching out. Can you please try to remove and install `react-native-svg` the following way:
`npm uninstall react-native-svg` or `yarn remove react-native-svg`
and then `expo install react-native-svg`

**Comment by gregdevvv** [comment]
> npm uninstall react-native-sv

I just tried this and am still getting the same error. I also attempted to do it with npm install react-native-svg@9.13.3 and was also still getting the error.

**Comment by gregdevvv** [comment]
Also it seems like last time the only way i was able to make the library work was downgrading to expo 46 (which initself then causes a bunch of other library issues i must manage),so it does seem like the issue does lie in expo 47 . This is something that has been very annoying especially for a paid product and i'm wondering if it could be addressed as swiftly as possible.

**Comment by santhoshvai** [comment]
hey @gregdevvv , I was able to [run our sample app on expo 47](https://github.com/GetStream/stream-chat-react-native/pull/1892).  Could you please verify if any other dependencies that you use are causing this

**Comment by gregdevvv** [comment]
<img width="710" alt="Screen Shot 2023-01-05 at 2 45 45 PM" src="https://user-images.githubusercontent.com/113376479/210867132-5176f756-b133-4c1d-8f17-4aca4f397072.png">

Here are the exact dependencies I have all downloaded , as a part of the expo StreamChat Tutorial. And with this package.json it does not run giving me the same Exception thrown while executing UI block.

**Comment by santhoshvai** [comment]
if possible, can you delete your ios folder and make expo generate them again and try.

Also, do you get a crash on android too.. if so, can you send us that please.

**Comment by gregdevvv** [comment]
There is no IOS and Android folder when using React Native with Expo in a normal managed project. The only time they will be there is when you manually establish a bare workflow in Expo thus introducing native modules . Previously in Expo 46 I was able to run the code library in a managed Expo project which was perfect ,and truly expo compatible.

**Comment by santhoshvai** [comment]
Hey @gregdevvv ,I was able to nail down this issue by [running android](https://user-images.githubusercontent.com/3846977/211314173-3281b752-1bd6-43a8-b212-2dc595467e0b.png) in the expo managed workflow. 

This is due to the combination of expo 47 and react-native-svg: 13.x. Unfortunately, you can't downgrade the react-native-svg to 12.x as with expo sdk 47 Managed Workflow the native code is pre-compiled compiled with "react-native-svg": "13.4.0". 

There are two ways to workaround this:

1. We can stick to expo 46 managed workflow for now and wait Expo 47 to update to a fixed react-native-svg version.
2. Generate native code for your project by doing [`expo prebuild`](https://docs.expo.dev/workflow/prebuild/). After doing this you can downgrade to react-native-svg: 12.x.  But be aware that you move out of the managed workflow. 

I am closing this issue as this is out of scope for us to fix in the SDK. Many thanks for raising this and making us aware of this!
