### ISSUE TITLE
Play received attachment audio Failed on ANDROID

### ISSUE THREAD

**Issue by amir-ibrahim** [GetStream/stream-chat-react-native#1937]
we are applying voice chatting our issue is when Start playing the received attachment audio stream file specifically on ANDROID ( everything works fine on IOS )  we use this lib to record and play the audio "react-native-audio-recorder-player" and this is the error:
LOG  startPlayer error=>  [Error: Prepare failed.: status=0x1]

**Comment by khushal87** [comment]
Hey @amir-ibrahim, we do not recommend using the library `react-native-audio-recorder-player` for playing audio in our SDK. We use `react-native-video` for audio and video and would recommend the same unless you have some different use case. Regardless. this problem seems related to the package you are using and doesn't seem related to our SDK. 

@vanGalilea has created a Whatsapp clone in the past using our SDK and used the package `react-native-audio-recorder-player`. Maybe you can refer to the code used in that project [here](https://github.com/GetStream/react-native-samples/tree/develop/projects/WhatsAppClone).

I will be closing this issue till then.

**Comment by amir-ibrahim** [comment]
Hello @khushal87 replaced my old lib with "react-native-video" and now I have a new error on android in the received chat voice " the voice chat I send worked fine" and the error is:
{"error": {"extra": -1010, "what": 1}}

![Screenshot_20230204_143234_Sanadak](https://user-images.githubusercontent.com/41516271/216765109-2733c9bd-b085-467e-9ab6-2eaf0311fc0b.jpg)
