### ISSUE TITLE
Custom Message Input Focusing

### ISSUE THREAD

**Issue by cleandevcode** [GetStream/stream-chat-react-native#1947]
Hello.

My work env:

```
"react-native" : "0.64.3",
"stream-chat": "7.1.0",
"stream-chat-react-native" : "^5.5.0"
```

I try to customize the message input.
Its my implementation.

```
      <MessageInput
        channel={channel}
        hasFilePicker={false}
        hasImagePicker={false}
        InputButtons={() => null}
        Input={() => <AutoCompleteInput />}
```

The main issue is that keyboard is dismissing automatically when typing a first character.
Once trying to type something, it works  fine.
Only keyboard is Dismissing when starting typing a first character.

Its not good experience, How can I fix it?

https://user-images.githubusercontent.com/52365167/216042523-608fc3bd-6f07-4774-8dec-00db2cd4691d.mov

**Comment by carolinaknoll** [comment]
Hi, @cleandevcode 👋 

I had the exact same issue as you. What fixed it for me was:

On my `MessageInput`, I called my custom Input component like this:

```tsx
<MessageInput
  Input={MyCustomInput} // notice I'm calling it directly instead of calling a function: () => MyCustomInput
/>
```

And then, inside my custom component, I needed to use `channel` so that when sending messages, audio or opening the attachment picker, it would know which channel to send the messages.

I used the `useChannelContext` hook to get the `channel`, like below:

```tsx
import { useChannelContext } from 'stream-chat-react-native'

const { channel } = useChannelContext()
```

Maybe it can help you as well!

**Comment by cleandevcode** [comment]
Thanks for your message. @carolinaknoll 
Btw on where did you use `channel` on your customized component?
Can you share some code snippets?

**Comment by carolinaknoll** [comment]
I needed it to use on a sub-component to record and send audio (just like Whatsapp where you can send audio recordings).
I also needed it to get the `id` of the channel (like this: `channel?.id`).

But you might not need it on your case, given the code you shared that shows you're using the `AutoCompleteInput` from stream-chat instead of using a custom component.

My custom component is a normal component just like any other:

```tsx
const ChatMessageInput = () => {
  const { channel } = useChannelContext()
  // useStates, etc

  return (
    // the views and other elements of the component
  )
}
```

**Comment by cleandevcode** [comment]
That`s great. My issue happened because of my code.
```
<MessageInput
  Input={MyCustomInput} // notice I'm calling it directly instead of calling a function () => <MyCustomInput/>
/>
```


Custom component should be called directly, NOT as a function.

Regards.

**Comment by carolinaknoll** [comment]
Awesome, so were you able to fix your issue, or do you need any more help? 😊

**Comment by cleandevcode** [comment]
Nope, I can solve this issue by using a direct component instead of function calling

**Comment by carolinaknoll** [comment]
I see, I'm glad you solved it! 😄 🚀
