### ISSUE TITLE
Triggers Warning on app background when typing events are turned off

### ISSUE THREAD

**Issue by TaharS** [GetStream/stream-chat-react-native#1997]
**Describe the bug**
We have setup our channel type to have Typing events turned off
<img width="664" alt="Screen Shot 2023-03-06 at 9 33 26 PM" src="https://user-images.githubusercontent.com/10080564/223329865-ddc8f77f-315d-4621-95d4-2eb795c89cb9.png">
However, while putting the app in background, it triggers an annoying warning
![log](https://user-images.githubusercontent.com/10080564/223330480-99dfc5c1-d38d-441b-8ff8-cace5dd5b941.png)
Probably coming from: https://github.com/GetStream/stream-chat-react-native/blob/develop/package/src/components/Channel/Channel.tsx#L642-L649

Doesn't seem to be a guardrail to send event that are turned off?

**Dev environment info (please complete/provide the following information):**
```
    "stream-chat": "8.2.1",
    "stream-chat-react-native": "^5.11.2",
```
- iPhone 14 Pro Emulator iOS 16

**To Reproduce**

1. Disable Typing events for a channel type in the backend
2. Open your app
3. go to a channel
4. Background the app (or background app selector)
5. Warning triggers

**Expected behavior**
No warnings, more graceful handling. It is an unhandled promise

**Comment by gma00** [comment]
We are seeing the same thing since we also have the Typing Events turned off. Anytime there is a request for `type: "typing.stop"` we are getting a 400 in the response with the same Error above. 
<img width="548" alt="Screen Shot 2023-03-07 at 11 28 33 AM" src="https://user-images.githubusercontent.com/20746619/223555596-b85850ad-c252-4c85-8aac-e84116370e8a.png">
