### ISSUE TITLE
[🐛] QueryMembers failed with error: "invalid json data"

### ISSUE THREAD

**Issue by Jonatthu** [GetStream/stream-chat-react-native#2235]
Latest stream packages.
iOS Simulator with xCode 15
QueryMembers failed with error: "invalid json data"

It does not fail on real device...
<img width="686" alt="image" src="https://github.com/GetStream/stream-chat-react-native/assets/3742176/ee6b3eb9-620b-4118-860b-86f16d93a635">

**Comment by vishalnarkhede** [comment]
Are you able to reproduce this consistently on even api call to queryMembers?

**Comment by vishalnarkhede** [comment]
Also please try to follow the issue template and provide as much information as possible from the template

**Comment by Jonatthu** [comment]
@vishalnarkhede yes many members of my team started to experience this on simulators after upgrading to xcode 15, or iOS17, the funny part is that the same code works when on a device targeting the same environment.

**Comment by vishalnarkhede** [comment]
hmm interesting ... looking into it

**Comment by jimmyphan** [comment]
This is also happening to me too

![image](https://github.com/GetStream/stream-chat-react-native/assets/5247055/608747eb-1603-40f5-83b3-d3d150b38178)

**Comment by joeporpeglia** [comment]
I don't use the react native package but I'm encountering the same issue using `stream-chat` in a react native app. These also started for me after upgrading to xcode 15 and ios 17. In the network inspector I can see that some of our requests are successful and one fails. For the failing request, the `payload` query param appears to be url encoded. Both of these are calling the `search` method on a channel instance.

Successful:
```
payload: {"filter_conditions":{"cid":REMOVED},"message_filter_conditions":{"pinned":true}}
```

Failing:
```
payload: %7B%22filter_conditions%22:%7B%22cid%22:%22REMOVED%22%7D,%22sort%22:[%7B%22field%22:%22created_at%22,%22direction%22:-1%7D],%22message_filter_conditions%22:%7B%22attachments.type%22:%7B%22$eq%22:%22poll%22%7D%7D%7D
```

**Comment by vishalnarkhede** [comment]
After some investigation, it turns out for some reason on iOS 17, request payload for all the `get` requests are getting double encoded.

Will let you know more, as the investigation continues.

**Comment by vishalnarkhede** [comment]
> the funny part is that the same code works when on a device targeting the same environment.

I just tried testing the same thing on real device with iOS 17, and the requests are failing there as well.

**Comment by vishalnarkhede** [comment]
This seems to help. But I can't say I understand the issue completely yet. So will keep digging

```tsx
    this.axiosInstance.defaults.paramsSerializer = (params) => {
      const newParams: any = {};
      for (let k in params) {
        if (typeof params[k] === 'object') {
          newParams[k] = JSON.stringify(params[k]);
        } else {
          newParams[k] = params[k];
        }
      }

      const str = qs.stringify(newParams);

      return str;
    }

```

**Comment by vishalnarkhede** [comment]
@joeporpeglia @Jonatthu whats the version of react-native that you are using?

**Comment by vishalnarkhede** [comment]
I have requested them for an update - https://github.com/facebook/react-native/commit/2be409ff55b50563a5f123f7823fa7cdb72dbef9#commitcomment-128920983

**Comment by joeporpeglia** [comment]
Nice find @vishalnarkhede! I'm running `react-native@0.72.5` (`expo@49.0.13`)

**Comment by vishalnarkhede** [comment]
## Issue

Ok so I think the solution is simply to not rely on axios's default encoding since it doesn't respect RFC 3986. This has been brought on axios repository multiple times, but not sure why its not prioritized - 

https://github.com/axios/axios/issues/4432

In iOS 17, NSURLs are now encoded according to RFC 3986 standards (as specified in https://www.ietf.org/rfc/rfc3986.txt), whereas they used to adhere to RFC 1738/1808 standards in earlier versions.

As a result of this change, the parsing algorithm of NSURL has been modified. When it encounters a reserved character, such as [, the parser will percent encode all possible characters in the URL, including %.

This adjustment can pose challenges for URLs that already have some form of encoding applied. For instance, if you have the string %22[], the updated parsing algorithm will yield the following outcomes:

Under RFC 1738/1808: `%22%5B%5D`
Under RFC 3986: `%2522%5B%5D` (which is considered an invalid encoding)

React Native tried fixing this issue here - but later they reverted the fix for some other reason:
- https://github.com/facebook/react-native/commit/9841bd81852d59608fe3566b17831d6d42eb7dcf
- reverted https://github.com/facebook/react-native/commit/2be409ff55b50563a5f123f7823fa7cdb72dbef9

## Solution

- Override axios's default encoder using `paramsSerializer`
- Make sure all the brackets are encoded. Best way would be to stringify the `object` type params
- And to make sure we follow RFC 3986, `qs` seems like the best option - as recommended by axios itself

```js
    this.axiosInstance.defaults.paramsSerializer = (params) => {
      const newParams: any = {};
      for (let k in params) {
        if (typeof params[k] === 'object') {
          newParams[k] = JSON.stringify(params[k]);
        } else {
          newParams[k] = params[k];
        }
      }

      const str = qs.stringify(newParams);

      return str;
    }
```

**Comment by vishalnarkhede** [comment]
Hey @joeporpeglia @Jonatthu could you please upgrade to `5.18.1-beta.3` and see if the issue is fixed?

**Comment by vishalnarkhede** [comment]
Please make sure version of `stream-chat` in your .lock file is `8.12.2`.

**Comment by joeporpeglia** [comment]
Just tried with `8.12.3` and everything looks good. Thanks for the quick fix @vishalnarkhede!

**Comment by vishalnarkhede** [comment]
Stable release `stream-chat-react-native@5.18.1` is ready now.
