### ISSUE TITLE
ActionSheet - componentWillReceiveProps warnings

### ISSUE THREAD

**Issue by leesolway** [GetStream/stream-chat-react-native#239]
The dependency on react-native-actionsheet is throwing warnings in the current version of react. Is there any plans to change this dependency?

```
* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: ActionSheet
```

gz#4460

**Comment by shodgetts** [comment]
Agent comment from Stephen Hodgetts in <a href='https://getstream.zendesk.com/agent/tickets/4460'>Zendesk ticket #4460</a>:<br><br>Assigned to **Vishal Narkhede**​

**Comment by virdesai** [comment]
@leesolway so that's an issue with a third party library we are using. we are undergoing some bigger changes soon which may address this issue or replace this library but for the time being you should be able to disable the warning with https://reactnative.dev/docs/debugging#console-errors-and-warnings (latest react native) or https://reactnative.dev/docs/0.62/debugging#warnings (previous react native versions)
