### ISSUE TITLE
[🐛] Url preview not working sometimes

### ISSUE THREAD

**Issue by cleandevcode** [GetStream/stream-chat-react-native#2482]
Hello, talents.
I have an issue when customizing the link preview.

My work env:
    "stream-chat": "7.1.0",
    "stream-chat-react-native": "^5.5.0",

Link Preview does not work sometimes.
What would be the reason and how can I fix that issue?

**Comment by khushal87** [comment]
Hey @cleandevcode, please give a brief description of what exactly you are trying to customize. What did you try, and what did not work? This would be easier to assist you better.

**Comment by cleandevcode** [comment]
@khushal87 Thanks for your response. 
This was my text which includes url.
`https://mesh.mymesh.io/mesh/event/invite/1f658d1e-5e6f-45a3-a9a2-94fd69a43e75`


<img width="362" alt="Screen Shot 2024-04-12 at 11 35 45 AM" src="https://github.com/GetStream/stream-chat-react-native/assets/52365167/906a9f62-3972-41a8-ab79-3af1292fd207">
As you can see, it does not generate the enriched preview at first, but from 2nd time, it generates preview.

How can i fix the issue?

**Comment by khushal87** [comment]
Hey @cleandevcode, this seems to be an issue on our backend and not something we control on the RN SDK. I have asked our support and backend team to look into this. Thanks 😄

**Comment by khushal87** [comment]
Hey @cleandevcode, since it's a backend request, I would suggest you reach out to the support team using https://getstream.io/contact/support/. They can look into it, and you can follow up there as well. The issue here would not do much of a value since it is not RN-specific. Please do not forget to mention this issue in your support request. Thanks, I will be closing this issue. 😄
