### ISSUE TITLE
Data only notification not triggered

### ISSUE THREAD

**Issue by krisnapy** [GetStream/stream-chat-react-native#2526]
I have problems with data only iOS that is not received from GetStream but is working with our server API It works properly.

How can we set the apns header same as mentioned [here](https://rnfirebase.io/messaging/usage#data-only-messages)?

**Comment by khushal87** [comment]
Hey @krisnapy, to enable data-only messages for iOS, you need to follow the instructions in [this documentation](https://getstream.io/chat/docs/sdk/reactnative/guides/push-notifications-v2/#make-ios-payload-data-only) and modify the notification template to support it. However, I recommend against using data-only notifications on iOS because Apple may not deliver the messages consistently. This information is also mentioned in our documentation about data-only notifications.

**Comment by krisnapy** [comment]
Hey @khushal87 thank you for your response, it's been activated data-only but the notification received inconsistently.

I will close this issue and find another alternative way to handle the message notification settings.
