### ISSUE TITLE
initial unread message count is always zero

### ISSUE THREAD

**Issue by sterlingwes** [GetStream/stream-chat-react-native#2635]
I'm trying to do a simple thing:
* in our app before a user sees the chat UI I want to mark how many unread messages there are for a specific channel (the user could be in multiple, I want separate counts for each)

Given the above, I figured I would call `countUnread()` on the channel to get the initial count of unread messages.

To test this I setup a channel with two users and had one user send a message to the channel before I loaded the UI in question for the second user.

**Problem**: I can not get the initial unread count to be anything but 0

I've tried the following code in our React Native app and in a minimal repro web app with the same result:

```typescript
const jwt = process.env.NEXT_PUBLIC_GS_JWT
const userId = process.env.NEXT_PUBLIC_GS_UID

const testGetStream = async () => {
  const client = StreamChat.getInstance(API_KEY)
  await client.connectUser({id: userId ?? ''}, jwt)

  const channels = await client.queryChannels({
    type: 'messaging',
    members: {$in: [userId ?? '']},
  })
  console.log(
    channels.map((channel) => ({
      id: channel.id,
      readInfo: channel.state.read,
    })),
  )

  const channel = channels.find((channel) => channel.id === 'MY_CHANNEL_ID')
  if (channel) {
    channel.sendMessage({text: 'hiya'})
  }
}

testGetStream()
```

As you can see, when the page loads I log the channel read state (thought reaching into `state` might give me more visibility than the count unread method would) and send a message to the channel. Second page to load should see an unread count of 1 due to the first page load sendMessage.

In the log output I see zeros for anything related to unread message counts. The `last_read` timestamp seems to be the time the page loaded, oddly enough - so it seems something in your backend system or in this library is marking the channel read before I can get an unread count.

**Comment by isekovanic** [comment]
Hi @sterlingwes , I spent quite a bit of time debugging this and trying to reproduce the issue - but to no avail (went so far as to spin up both custom apps as well as using channel querying directly to see the values). In all instances, I have found that:

- `channel.countUnread()` returns the correct value (for each user too, both in scenarios of programmatically triggering `sendMessage` as well as doing it manually within a channel)
- `channel.state.read[<some-user-id>]` has all of the correct values (`last_read` seems consistent and correct, `last_read_message_id` is correct and `unread_messages` is correct and updating in real time for me)
- I also tested the case of `last_read` being updated prematurely (while simply browsing the channels and not actually reading the messages) and this does not seem to be the case any longer

I'm under the impression that the issue most likely got fixed since it was reported (since it's really been a while, apologies for that !), or perhaps I'm doing something wrong while debugging. If you're available and up for it, would you be willing to give it a brief look on whether you can still reproduce this ?

If not then we can close the issue and reopen it if something similar still persists.

Thanks a ton for your analysis !

**Comment by khushal87** [comment]
Closing this issue for long time of inactivity and unabable to reproduce it. This might be fixed with past releases. Please upgrade to the latest version and let us know. Feel free to reopen it if you still see this as an issue.

**Comment by bense30** [comment]
I am having the same issue using stream-chat-expo. Just reinstalled to 5.44.2 and having the same issue. 

After this code the data in the event `await channel.markUnread({ message_id: "<message_id>" });` still shows total_unread_count, unread_count and unread_messages all as 0. unread_channels is set to 1.
