### ISSUE TITLE
🔥 [🐛] AttachmentPicker BottomSheet is very slow on Android

### ISSUE THREAD

**Issue by yefim** [GetStream/stream-chat-react-native#2750]
## Issue

Loading the initial `<Chat />` stream component is very slow on Android, taking >200ms to render the BottomSheets inside of AttachmentPicker. These bottom sheets aren't displayed. There is no way to disable the AttachmentPicker. This makes Stream React Native on Android have abysmal performance.

<img width="1728" alt="Screenshot 2024-11-01 at 10 24 05 AM" src="https://github.com/user-attachments/assets/34b21203-9b0e-403d-96c9-8eb328a9bc31">

<img width="1728" alt="Screenshot 2024-11-01 at 3 36 24 PM" src="https://github.com/user-attachments/assets/263807ac-bc5c-45a9-8d5e-54175448da61">

### Steps to reproduce

1. Have a screen with a component that renders:

```jsx
    <OverlayProvider value={{ style: streamTheme }}>
      <Chat client={streamChatClient}>{children}</Chat>
    </OverlayProvider>
```

2. Open that screen
3. Wait >200ms for the screen to open

### Expected behavior

The screen to open in a timely manner

## Environment

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
  "dependencies": {
    "@gorhom/bottom-sheet": "4.6.4",
    "@gorhom/portal": "1.0.14",
    "@stream-io/flat-list-mvcp": "0.10.3",
    "expo": "51.0.18",
    "react-native": "0.74.3",
    "stream-chat": "8.38.0",
    "stream-chat-expo": "5.36.2"
  }
}

```

**`react-native info` output:**

```
System:
  OS: macOS 14.4.1
  CPU: (12) arm64 Apple M2 Pro
  Memory: 64.66 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.13.1
    path: ~/.nvm/versions/node/v20.13.1/bin/node
  Yarn:
    version: 1.22.22
    path: ~/.nvm/versions/node/v20.13.1/bin/yarn
  npm:
    version: 10.5.2
    path: ~/.nvm/versions/node/v20.13.1/bin/npm
  Watchman:
    version: 2024.07.15.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.4
      - iOS 17.4
      - macOS 14.4
      - tvOS 17.4
      - visionOS 1.1
      - watchOS 10.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.18034.62.2411.12071903
  Xcode:
    version: 15.3/15E204a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.12
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

- **Platform that you're experiencing the issue on**:
    - [ ] iOS
    - [x] Android
    - [ ] **iOS** but have not tested behavior on Android
    - [x] **Android** but have not tested behavior on iOS
    - [ ] Both
- **`stream-chat-react-native` version you're using that has this issue:**
    - 5.36.2
- Device/Emulator info:
  - [ ] I am using a physical device
  - OS version: Android 13.0
  - Device/Emulator: Pixel 6 emulator

</p>
</details>

**Comment by isekovanic** [comment]
Hi @yefim ,

@khushal87 already replied on Slack but adding this here as well for brevity:

- To disable the `AttachmentPicker`, on needs to uninstall `@react-native-camera-roll/camera-roll` from their project dependencies and it will stop appearing
- As a drop in replacement for it, our [Native Image Picker](https://getstream.io/chat/docs/sdk/reactnative/guides/native-image-picker/) will be displayed instead
- If you're not using any attachment picker (so neither `@react-native-camera-roll/camera-roll` nor `react-native-image-picker`), you might also want to disable `hasImagePicker` as a [`Channel` prop](https://getstream.io/chat/docs/sdk/reactnative/core-components/channel/#hasimagepicker) so that the icon doesn't show

And alternative (if you're not using any attachment picker) would also be to use [this prop](https://getstream.io/chat/docs/sdk/reactnative/core-components/channel/#attachbutton) on the `Channel` component and set it to `AttachButton={() => null}`. It should also make sure that the `BottomSheet` is never rendered.

We're aware of the issues the underlying `BottomSheet` has which is why we are moving to a different approach come `v6`. Until
