### ISSUE TITLE
iPhone unable to upload a video via upload a file

### ISSUE THREAD

**Issue by lokewk** [GetStream/stream-chat-react-native#479]
**Describe the bug**
For iPhone, when upload a file is pressed, there is no option to select a video from phone gallery (only icloud drive, on my iphone , recently deleted and downloads is available)

**Dev environment info (please complete/provide the following information):**

"stream-chat": "2.6.0",
"stream-chat-expo": "^2.1.0",
"expo": "^39.0.0",
iPhone X iOS 13.6.1

**To Reproduce**

1. Go to Chat conversation screen
2. Click on 'attach button'
3. Click on 'upload a file'
4. Sees 'On my iphone' screen. 

gz#8428

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/8428'>Zendesk ticket #8428</a>:<br><br>Hi

Thanks for the details.
We will check this and get back to you soon.

Cheers
Seetha

**Comment by lokewk** [comment]
Any updates? @shodgetts

**Comment by virdesai** [comment]
@lokewk can you leave the app and go find the video within Photos. then long press it to open the context menu and then select `Share`. then scroll down to the `Save to Files` option and select that. you should now be able to access that video in your files within the app. I believe iOS segregates photos from files in some odd way because they provide this option so it's not able to be navigated to within their file manager otherwise

**Comment by lokewk** [comment]
@virdesai Thanks for the explanation. sadly is not acceptable from UX point. Will there be any update from your side to overcome this?

**Comment by vishalnarkhede** [comment]
@lokewk I guess thats a platform limitation. We use this library for file picker functionality, which is pretty standard library in RN community - https://github.com/rnmods/react-native-document-picker

**Comment by shodgetts** [comment]
Agent comment from Vishal Narkhede in <a href='https://getstream.zendesk.com/agent/tickets/8428'>Zendesk ticket #8428</a>:<br><br>Hey,

I am closing this ticket for now. Please let us know if you have more questions.

Thanks,
Vishal
