### ISSUE TITLE
Upgrade helper wiki page is missing 2.x -> 3.x path

### ISSUE THREAD

**Issue by wodow** [GetStream/stream-chat-react-native#615]
https://github.com/GetStream/stream-chat-react-native/wiki/Upgrade-helper is prominently linked from the project's [main README](https://github.com/GetStream/stream-chat-react-native/blob/master/README.md) but does not mention the 3.x major version, or how to upgrade to it from 2.x

**Comment by vishalnarkhede** [comment]
Hey @wodow We don't have upgrade helper for v3 of SDK, since it's a major architectural change to SDK and it's not possible to write down every change in upgrade helper. I would recommend you to read our HOC component descriptions here - https://github.com/GetStream/stream-chat-react-native/wiki/Cookbook-v3.0#components

**Comment by wodow** [comment]
Understood. IMHO your post here would be a useful alternative to nothing in the Upgrade helper document!
