### ISSUE TITLE
Connection on background / locked screen

### ISSUE THREAD

**Issue by aniciom** [GetStream/stream-chat-react-native#73]
I've a question i didn't test it, maybe any of the developers did and can answer it, in case i launch my app in android or ios and leave it in background, and i lock the screen, and i leave the app hanging around in the bg, my question is the socket connection keeps alive or gets closed? from what i've seen if its get closed it tries to connect again, another question related to this, once the connection gets recovered it retrieves all the missed messages in the meanwhile? that would help me to take the correct actions once the app is back to foreground.

Maybe its more related to stream-chat-js library because i'm using outside the steam-chat-react- reactive, by my side lets say.

Thanks in advance

**Comment by vishalnarkhede** [comment]
Hey @aniciom 

When the app goes to background, sock connection will stay alive for 5-10 seconds (currently we are not controlling it), after that it breaks. And once app comes to foreground, we recover the socket connection and re-query the channels.

Let me know if that answers your question.

**Comment by aniciom** [comment]
Yep it does, Thanks

**Comment by aniciom** [comment]
Sorry @vishalnarkhede I reopen it for a second thing, i'm using stream-chat-js outside stream-chat-react-native, what you described above its the behaviour of the library or the behaviour of the app?

**Comment by vishalnarkhede** [comment]
Connection/reconnection logic is in `stream-chat-js` or js client. It is not aware of AppState, but after 10-15 seconds in background, operating system breaks the network connection for the app automatically - and thus socket connection breaks. After this, js client keeps trying to connect at regular interval. 

When app comes to foreground, app is given access to internet again - `NetInfo` detects the network connection and we/app inform the js client that network connection has been recovered, so that it can attempt socket connection immediately.

This is the code where we inform js client about network change - https://github.com/GetStream/stream-chat-react-native/blob/master/src/components/Chat.js#L72

Hope that helps :)

**Comment by aniciom** [comment]
Yep i've been digging a little bit into the internals, but since i'm using my own app i think i'd have to implement a similar logic inside of it, because i'm not using the stream's chat app only the js's library, but having the stream chat react native as main example i think i can get out some features like the one i need.

Thanks @vishalnarkhede

**Comment by rohanvasishth** [comment]
Hi, @vishalnarkhede.

Thanks for providing some insight on this issue. I had a question about concurrent connections. When you remove the connection after 10-15 seconds in background, I am assuming that user is no longer being counted as a concurrent connection right?

I have been trying to test it by entering a background state in some of my devices and seeing what the max concurrent connections becomes but it seems like these devices may be still being counted as connected. I just want to make sure that isn't the case.
