### ISSUE TITLE
unable to save image on android

### ISSUE THREAD

**Issue by zT0Tz** [GetStream/stream-chat-react-native#858]
In ImageGallery when I click the the button on left bottom corner, the menu will pop up. In ios I have the option to save image, however in android I can only share image but not save it.

stream-chat-react-native: v3.8.0
react-native: v0.63.2

IOS:

<img src="https://user-images.githubusercontent.com/26011653/133654589-f4186722-241e-4f15-98eb-bb1f80c3adf0.jpg" width="350" height="700">   <img src="https://user-images.githubusercontent.com/26011653/133654079-3bb92871-e0c8-426d-8595-94ef486e2060.png" width="350" height="700">

Android:

<img src="https://user-images.githubusercontent.com/26011653/133654144-18ae2529-8844-43d8-8b4b-51369f768ee0.png" width="350" height="700">     <img src="https://user-images.githubusercontent.com/26011653/133654155-510f20b1-3a60-4509-ac8c-62035ddf3062.png" width="350" height="700"> 

gz#15173

**Comment by streamiosupport** [comment]
Agent comment from Cody Smith in <a href='https://getstream.zendesk.com/agent/tickets/15173'>Zendesk ticket #15173</a>:<br><br>Hi, thank you for those details.
I'll take a look into this and get back to you as soon as I can with more info.

Regards
-Cody
<br><p><em><small>°°°</small></em></p>

**Comment by streamiosupport** [comment]
Agent comment from Cody Smith in <a href='https://getstream.zendesk.com/agent/tickets/15173'>Zendesk ticket #15173</a>:<br><br>Request #15175 "Unable to close the ImageGrid po..." was closed and merged into this request. Last comment in request #15175:

**Describe the bug**

In ImageGallery when click the grid button on the right bottom, the ImageGrid will popup. In ios click the close button will bring we back to the previous ImageGallery view, however in android the close button doesn't work. Only way to get back is using the back navigator button of android system, this will send me back to message list. After press on an image again, it will still be in ImageGrid, can't go back to ImageGallery view again.

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native/stream-chat-expo):  v3.8.0
- react-native or expo version:  v0.63.2
- Device/Emulator (android/ios) and OS version: emulator(android version 10), and real devices

**To Reproduce**
Steps to reproduce the behavior:

1. Go to ImageGallery,
2. Click on grid button on the right bottom to see ImageGrid
3. Click close button on top right corner
4. can not close it

**Expected behavior**
ImageGrid should close

**Screenshots**
<img src="https://user-images.githubusercontent.com/26011653/133658359-7f5c62f1-af64-495e-8d29-9aea9c3eb805.png" width="350" height="700">  <img src="https://user-images.githubusercontent.com/26011653/133658387-a0a24483-d629-4663-b30c-6697d981d610.png" width="350" height="700">
<br><p><em><small>°°°</small></em></p>

**Comment by vishalnarkhede** [comment]
Hey @zT0Tz We use a third party dependency for share functionality - https://react-native-share.github.io/react-native-share/docs/share-single

So this is not something we can fix on our side. But if you want to modify share functionality, you can override the handler -  [`shareImage`](https://github.com/GetStream/stream-chat-react-native/blob/develop/package/native-package/src/index.js#L165). You can find more details about overriding native handlers in following docs - https://getstream.io/chat/docs/sdk/reactnative/customization/native_handlers/#overriding-handlers
