### ISSUE TITLE
How to trigger a ChannelList update

### ISSUE THREAD

**Issue by RomanBob123** [GetStream/stream-chat-react-native#931]
Is there a way to trigger the update of this ChannelList from the outside?

gz#15876

**Comment by madsroskar** [comment]
Hi, @RomanBob123. 

In the `ChannelsContext`, there is a function exposed named [`refreshList`](https://getstream.io/chat/docs/sdk/reactnative/contexts/channels-context/#refreshlist) - would this do what you're aiming to do?

> Function to manually resync or refresh the channels in ChannelList component.

**Comment by madsroskar** [comment]
Another way you could force a rerender/reload of the `ChannelList` component is to set a `key` prop on the ChannelList and update the value of this prop. For example:

```
const WrapperComponent = ({ someProp }) => {
    const [key, setKey] = useState(0);

    useEffect(() => {
        setKey((previousKey) => previousKey + 1);
    }, [someProp])

    return (<ChannelList client={myChatClient} key={key} />)
}
```
In the example above, the ChannelList should reload each time `setKey` is called since `key` will have a new value.

-----

The Issue section of this Github repo is now reserved only for bug reports and feature improvements and suggestions. It looks like what you’re looking for is technical support using the product. For this support in the future, we would suggest emailing our Customer Success and Engineer support team at support@getstream.io with your application key or ID, and we’ll be able to help you out. 

Thanks for your understanding. We’re going to mark this issue as closed.
In case our understanding is incorrect, and you are describing a bug, we apologize, and invite you to please follow up with a minimal reproduction of the bug and we will reopen the issue and investigate accordingly.

**Comment by cleandevcode** [comment]
Yes, on my side 2nd option worked well.
Btw, I also tried to use 1st option by using `useChannelsContext`

But `refreshList` was undefined.

```
import {useChannelsContext} from 'stream-chat-expo'
...
const {refreshList} = useChannelsContext()

```

It would be helpeful why `refreshList` returns `undefined`.


My stacks:

```
stream-chat: 6.1.0
stream-chat-expo: ^4.1.0
```

Thanks
