### ISSUE TITLE
Click on a channel in ChannelList component doesn't work on Android

### ISSUE THREAD

**Issue by mishkeTz** [GetStream/stream-chat-react-native#976]
**Describe the bug**
Click on a chat in ChannelList component is not triggered on Android, while it works fine on IOS.

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native): ^3.8.3
- react-native: ~0.63.4
- Emulator: Android/API 30, 11.0

**Expected behavior**
The **onSelect** prop of ChannelList component gets called.

**Additional context**
I have:
    - Tab navigator
        - Stack navigator (ChatsList -> Chat -> Thread)

If I try to pass my custom Preview component (for testing i.e. TouchableOpacity with onPress) then it works, but currently the **onSelect** prop of ChannelList never gets triggered on Android.
The implementation is done based on this tut https://github.com/GetStream/stream-chat-react-native/wiki/Tutorial-v3.0#message-threads

**Screenshots**
<img width="401" alt="Screenshot 2021-11-03 at 17 58 59" src="https://user-images.githubusercontent.com/15350199/140120710-6ae9b1ad-be84-4a19-ae22-263514fb95c2.png">

gz#16408

**Comment by vishalnarkhede** [comment]
Hey @mishkeTz We tried to reproduce this issue on latest version of stream-chat-react-native SDK our [TypescriptMessaging](https://github.com/GetStream/stream-chat-react-native/tree/develop/examples/TypeScriptMessaging) example application, but unfortunately couldn't. 

It would really help us if you can cut a separate branch and help us reproduce the issue in this example app.

**Comment by mishkeTz** [comment]
Hi @vishalnarkhede,
Thank you for fast reply, I was able to create a git with a reproducible error that happens in my case, it might be related to navigators: Stack -> Tab -> Stack (not sure);

Here's the link to the gist [https://gist.github.com/mishkeTz/b26ec44bfef1bf56614a67d036e77142](https://gist.github.com/mishkeTz/b26ec44bfef1bf56614a67d036e77142)

In the comment you can see the list of dependencies used in the project.

**Comment by vishalnarkhede** [comment]
Thanks @mishkeTz I will check it out and get back to you

**Comment by vishalnarkhede** [comment]
Hey @mishkeTz I tried to replicate the issue using the code snippet you provided in our example application, but unfortunate couldn't. There are few differences in versions of dependencies though (between our example app and gist which you shared)

- `react-native`
- `react-native-gesture-handler` (not sure what version you are using)
- `@react-navigation/stack`

Is it possible for you to upgrade these dependencies and test it again? 

I tried to do some research around this issue and quite a few people have face this issue. This issue seems to be due to using react-native-gesture-handler and @react-navigation/native-stack (e.g., [this issue](https://github.com/software-mansion/react-native-screens/issues/483#issuecomment-621102252)). We use TouchableOpacity from gesture handler within the SDK for performance purpose (as mentioned [here](https://docs.swmansion.com/react-native-gesture-handler/docs/api/components/touchables))

**Comment by mishkeTz** [comment]
I was able to fix it! Thank you!

However I'm experiencing other weird issues now on Android. I'm not sure if it's related to GetStream or not. On the same example when I try to navigate between Channels sometimes the ChannelListScreen gets stuck, there's like this white-transparent overlay (can notice it on the picture) and sometimes when I navigate to Channel screen it's completely white but I'm still able to blindly click on the back button and then I get back to ChannelListScreen.

Do you have any idea what's going on there? I tried it on emulator and real device, same behaviour.

<img width="401" alt="Screenshot 2021-11-05 at 21 20 30" src="https://user-images.githubusercontent.com/15350199/140573869-e491fd84-97b4-40f1-b4fb-276d532b01a7.png">

**Comment by mishkeTz** [comment]
After testing it a little deeper I realised that I was using:
`import { createNativeStackNavigator } from '@react-navigation/native-stack';`
for Stack navigator, once I changed that to:
`import {createStackNavigator} from '@react-navigation/stack';`
the issue was fixed.

This issue can be closed! Thanks for the help!

**Comment by vishalnarkhede** [comment]
Thanks for the update @mishkeTz :)
